const $api=s=>document.querySelector(s);
const apiModal=$api('#apiModal'),apiMethod=$api('#apiMethod'),apiUrl=$api('#apiUrl'),apiHeaders=$api('#apiHeaders'),apiBody=$api('#apiBody'),apiSend=$api('#apiSend'),apiClear=$api('#apiClear'),apiClose=$api('#apiClose'),apiOutput=$api('#apiOutput'),apiStatus=$api('#apiStatus'),apiDuration=$api('#apiDuration');
function openApi(){apiModal.classList.add('open');apiModal.setAttribute('aria-hidden','false');setTimeout(()=>apiUrl.focus(),30)}
function closeApi(){apiModal.classList.remove('open');apiModal.setAttribute('aria-hidden','true')}
function parseJson(text,label){if(!text.trim())return {};try{return JSON.parse(text)}catch(e){throw new Error(`${label} は正しいJSONにしてください: ${e.message}`)}}
async function sendApi(){const method=apiMethod.value,url=apiUrl.value.trim();if(!url){apiOutput.textContent='URLを入力してください。';apiOutput.classList.add('error');return}let headers,body;
  try{headers=parseJson(apiHeaders.value,'Headers');body=parseJson(apiBody.value,'Body')}catch(e){apiOutput.textContent=e.message;apiOutput.classList.add('error');return}
  apiStatus.textContent='Requesting…';apiDuration.textContent='';apiOutput.classList.remove('error');apiOutput.textContent='リクエスト中…';const started=performance.now();
  const options={method,headers};if(!['GET','HEAD'].includes(method)&&apiBody.value.trim()){options.body=JSON.stringify(body);if(!Object.keys(headers).some(k=>k.toLowerCase()==='content-type'))options.headers={...headers,'Content-Type':'application/json'}}
  try{const response=await fetch(url,options);const elapsed=Math.round(performance.now()-started);apiDuration.textContent=`${elapsed} ms`;apiStatus.textContent=`${response.status} ${response.statusText}`;const text=await response.text();let formatted=text;try{formatted=JSON.stringify(JSON.parse(text),null,2)}catch{}apiOutput.textContent=formatted||'(empty response)';if(!response.ok)apiOutput.classList.add('error')}catch(e){apiDuration.textContent=`${Math.round(performance.now()-started)} ms`;apiStatus.textContent='Failed';apiOutput.textContent=`API request failed\n\n${e.message}\n\nヒント: 相手APIがCORSを許可している必要があります。ブラウザから直接呼べないAPIは、将来のサーバー側proxyで対応できます。`;apiOutput.classList.add('error')}}
$api('#apiBtn').addEventListener('click',openApi);apiClose.addEventListener('click',closeApi);apiModal.addEventListener('click',e=>{if(e.target===apiModal)closeApi()});apiSend.addEventListener('click',sendApi);apiClear.addEventListener('click',()=>{apiOutput.textContent='レスポンスがここに表示されます。';apiOutput.classList.remove('error');apiStatus.textContent='Ready';apiDuration.textContent='' });document.addEventListener('keydown',e=>{if(e.key==='Escape')closeApi()});
